from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "STATUS.md"
DESTINATION = ROOT / "docs" / "current-status.md"


def render() -> str:
    text = SOURCE.read_text(encoding="utf-8")
    text = text.replace("# Project status\n", "# Current project status\n", 1)
    text = text.replace(
        "# Current project status\n",
        "# Current project status\n\n"
        "> Generated from the authoritative root [STATUS.md](../STATUS.md). "
        "Do not edit this file directly; run python scripts/sync_current_status.py.\n",
        1,
    )
    text = re.sub(r"\]\(docs/", "](", text)
    return text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = DESTINATION.read_text(encoding="utf-8") if DESTINATION.is_file() else ""
        if actual != expected:
            raise SystemExit("docs/current-status.md is out of sync with STATUS.md")
        return 0
    DESTINATION.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
